[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "caesar"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "torch>=2.0",
  "numpy",
  "scipy",
  "tqdm",
  "biopython",
  "chex",
  "immutabledict",
  "ml-collections",
  "pydssp",
  "dm-tree",
  "jax[cpu]==0.5.0",
  "dm-haiku==0.0.16",
  "flexloop @ git+https://github.com/mjendrusch/flexloop.git",
  "gemmi",
  "pytest>=7.0",
  "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/c9llm3bones/caesar"
Source = "https://github.com/c9llm3bones/caesar"
Issues = "https://github.com/c9llm3bones/caesar/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.setuptools]
packages = ["caesar"]
