"""Geometry module — PyTorch geometric operations for proteins."""

# Import all geometry classes and functions from geometry.py
from .geometry import (
    rot_matmul,
    rot_vec_mul,
    batch_pairwise_dist,
    pairwise_dist,
    extract_aa_frames,
    extract_neighbours_salad_compatible as extract_neighbours,
    extract_neighbours as extract_neighbours_legacy,
    get_neighbours,
    get_index_neighbours,
    get_spatial_neighbours,
    get_random_neighbours,
    distance_rbf,
    distance_one_hot,
    index_sum,
    index_mean,
    axis_index,
    index_align,
    sequence_relative_position,
    bond_angle,
    dihedral_angle,
    single_protein_sidechains,
    index_count
)

__all__ = [
    "rot_matmul",
    "rot_vec_mul",
    "batch_pairwise_dist",
    "pairwise_dist",
    "extract_aa_frames",
    "extract_neighbours",
    "extract_neighbours_legacy",
    "get_neighbours",
    "get_index_neighbours",
    "get_spatial_neighbours",
    "get_random_neighbours",
    "distance_rbf",
    "distance_one_hot",
    "index_sum",
    "index_mean",
    "axis_index",
    "index_align",
    "sequence_relative_position",
    "bond_angle",
    "dihedral_angle",
    "single_protein_sidechains",
    "Vec3",
]
